### ISSUE TITLE
Admin bar should render in iframe from site domain

### ISSUE THREAD

**Issue by goldenapples** [fusioneng/ext-admin-menu#1]
To prevent requiring auth cookies from being served on external domains, the admin bar will have to be served in, or attached to, an iframe served from the same domain and protocol as the admin is.

**Comment by matthewdorman** [comment]
With some updates in #5 you can put the sample/index.html file on any domain and the JSONP request reads the Auth cookie from the admin domain. Here's the query string to append for testing:

index.html?domain=http:%2F%2Ffusion.local&type=post&id=288041#link1

**Comment by goldenapples** [comment]
As we discussed, it shouldn't be necessary to load this admin bar in an iframe. The jsonp/callback structure worked on here is enough to accomodate almost any scenario I can think of.

We're requesting the admin bar script as a normal front-end request to the admin site's domain, so we get the benefits of page caching for non-logged-in users, and we still pass the normal logged-in cookies for users who are logged in.
